/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EscuelaVisual.IngresoDatos;

import EscuelaPackage.Colegio;
import EscuelaPackage.Curso;
import EscuelaPackage.Planificacion;
import EscuelaVisual.OpcionesCurso;
import Generar.GuardarXML;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBException;

/**
 *
 * @author Ignacio Esparza
 */
public class IngPlanificaciones extends javax.swing.JFrame {

    DefaultTableModel modeloP;
    GuardarXML gx = new GuardarXML();
    Colegio college = gx.cargar();
    int pos;
    int materia = -1;
    Curso curso;

    public IngPlanificaciones() {
        initComponents();
        setLocationRelativeTo(null);
        modelo();
    }

    public void modelo() {
        String cabecera[] = {"Número Plan", "Planes"};
        String datos[][] = {};
        modeloP = new DefaultTableModel(datos, cabecera);
        JTPlanificaciones.setModel(modeloP);

    }

    public void planes(Curso plan, int posicion) {

        if (plan.getProfesor().getAsignaturaP().getMateria().equals("Matemáticas")) {
            materia = 0;
        }
        if (plan.getProfesor().getAsignaturaP().getMateria().equals("Lenguaje")) {
            materia = 1;
        }
        if (plan.getProfesor().getAsignaturaP().getMateria().equals("Historia")) {
            materia = 2;
        }
        if (plan.getProfesor().getAsignaturaP().getMateria().equals("Inglés")) {
            materia = 3;
        }
        if (plan.getProfesor().getAsignaturaP().getMateria().equals("Ciencias")) {
            materia = 4;
        }
        for (int i = 0; i < 10; i++) {
            String datosMate[] = {"Plan " + (i + 1),
                plan.getAsignaturaC()[materia].getActividades()[i].getActividad()};

            modeloP.addRow(datosMate);
        }
        PlanMateria.setText("Planificaciones : " + plan.getProfesor().getAsignaturaP().getMateria());
        curso = plan;
        pos = posicion;
    }

    public void obtenerPlanes() throws JAXBException, FileNotFoundException {

        Planificacion[] plan = new Planificacion[10];
        for (int i = 0; i < plan.length; i++) {
            plan[i] = new Planificacion((String) JTPlanificaciones.getValueAt(i, 1));
        }
        college.getTCursos()[pos].getAsignaturaC()[materia].setActividades(plan);
        gx.guardar(college);
        JOptionPane.showMessageDialog(null, "Exito");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTPlanificaciones = new javax.swing.JTable();
        PlanMateria = new javax.swing.JLabel();
        GuardarPlanes = new javax.swing.JButton();
        VolverAOpcCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTPlanificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTPlanificaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTPlanificaciones);
        if (JTPlanificaciones.getColumnModel().getColumnCount() > 0) {
            JTPlanificaciones.getColumnModel().getColumn(0).setResizable(false);
            JTPlanificaciones.getColumnModel().getColumn(1).setResizable(false);
            JTPlanificaciones.getColumnModel().getColumn(2).setResizable(false);
            JTPlanificaciones.getColumnModel().getColumn(3).setResizable(false);
        }

        PlanMateria.setText("Planificaciones");

        GuardarPlanes.setText("Guardar");
        GuardarPlanes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPlanesMouseClicked(evt);
            }
        });
        GuardarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPlanesActionPerformed(evt);
            }
        });

        VolverAOpcCurso.setText("Volver");
        VolverAOpcCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAOpcCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlanMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarPlanes)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverAOpcCurso)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanMateria)
                    .addComponent(GuardarPlanes))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VolverAOpcCurso)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverAOpcCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAOpcCursoActionPerformed
        OpcionesCurso oc = new OpcionesCurso();
        oc.SelectCurso(college.getTCursos()[pos], pos);
        oc.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverAOpcCursoActionPerformed

    private void GuardarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPlanesActionPerformed
        try {
            obtenerPlanes();
        } catch (JAXBException ex) {
            Logger.getLogger(IngPlanificaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IngPlanificaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarPlanesActionPerformed

    private void GuardarPlanesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPlanesMouseClicked

    }//GEN-LAST:event_GuardarPlanesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngPlanificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngPlanificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngPlanificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngPlanificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngPlanificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarPlanes;
    private javax.swing.JTable JTPlanificaciones;
    private javax.swing.JLabel PlanMateria;
    private javax.swing.JButton VolverAOpcCurso;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
